replicaCount: 1

image:
  repository: vucongtuanduong/grading-executor
  tag: "latest"
  pullPolicy: Always

service:
  port: 8083
  nodePort: 30003

spring:
  profilesActive: stg

config:
  serverUrl: "http://config-server:8086"

secrets:
  dbSecret: "db-secret"

resources:
  requests:
    cpu: 500m
    memory: 512Mi
  limits:
    cpu: "1"
    memory: 1Gi
